app:
    resource: '@AppBundle/Controller/'
    type: annotation

oneup_uploader:
    resource: .
    type: uploader
inicio:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: inicio.twig
logout:
    path: /logout
clients_logout:
    path: /clients_logout