security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt

    providers:
        Usuario:
            entity:
                class: AppBundle:Usuario
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            pattern: .*
            methods: [GET, POST]
            provider: Usuario
            form_login:
                check_path: login
                login_path: login

                # Login correctamente
                always_use_default_target_path: false
                default_target_path: inicio
                target_path_parameter: _target_path
                use_referer: false

                # Login erroneo
                failure_path: login
                failure_forward: false
                failure_path_parameter: _failure_path

                # Parametros para formulario de login
                username_parameter: _correo
                password_parameter: _password

                # Protección csrf
                csrf_token_generator: security.csrf.token_manager

                # Solo permite login a traves del metodo post
                post_only: true

                # Guarda la sesion para evitar doble login
                require_previous_session: true
            logout:
                path: logout
                target: login
                invalidate_session: false
            security: true
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/marina/cotizacion/gracias, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/marina/cotizacion/.*/confirma, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/astillero/gracias, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/astillero/.*/confirma, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*, roles: IS_AUTHENTICATED_FULLY }
